En este ejercicio tenemos los datos mal colocados. Los tenemos por filas. En cada fila tenemos el dato de lo que debería ser una columna distinta. Así no nos valen los datos. Tenemos que tenerlos colocados por columnas. Es decir, hay que decidir que tendrá en común cada fila y que datos tienen que estar representados en columnas.

In [1]:
import pandas as pd
obesidad = pd.read_csv("Obesidad.csv")
print(obesidad.columns)

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

Al mirar el head, te tienes que dar cuenta de varias cosas. La primera, que cada dato corresponde a un año y un estado de Estados Unidos. Por ejemplo, el primero es de Albama 2011. Para verlo mejor, vamos a quitar algunas columnas.

In [2]:
obesidad.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Total,Total,OVR,OVERALL
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Female,GEN,FEMALE
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,Less than high school,EDU,EDUHS
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,High school graduate,EDU,EDUHSGRAD

In [3]:
obesidad_recortado = obesidad[['YearStart','YearEnd','LocationAbbr','Question','Data_Value','Stratification1']]

Al quedarnos solo con estas columnas vemos más claro como están los datos. La primera fila corresponde a el porcentaje de adultos (Total) de más de 18 años que tienen obesidad en Alabama en 2011. El valor del dato está en Data_Value. Además vemos que el segundo dato corresponde a solo los hombres, el tercero a las mujeres... Esta división de la población está en Stratificacion1. Por tanto, esta columna nos va a ser de utilidad.

In [4]:
obesidad_recortado.head()

,YearStart,YearEnd,LocationAbbr,Question,Data_Value,Stratification1
0,2011,2011,AL,Percent of adults aged 18 years and older who ...,32.0,Total
1,2011,2011,AL,Percent of adults aged 18 years and older who ...,32.3,Male
2,2011,2011,AL,Percent of adults aged 18 years and older who ...,31.8,Female
3,2011,2011,AL,Percent of adults aged 18 years and older who ...,33.6,Less than high school
4,2011,2011,AL,Percent of adults aged 18 years and older who ...,32.8,High school graduate

El siguiente paso va a ser cambiar los nombres de las preguntas. Estos nombres son demasiado largos y poco representativos a simple vista.

In [ ]:
obesidad_recortado['Question'].unique()

array(['Percent of adults aged 18 years and older who have obesity',
       'Percent of adults aged 18 years and older who have an overweight classification',
       'Percent of adults who report consuming fruit less than one time daily',
       'Percent of adults who report consuming vegetables less than one time daily',
       'Percent of adults who engage in muscle-strengthening activities on 2 or more days a week',
       'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)',
       'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week',
       'Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)',
       'Percent of adults who engage in no leisure-time physical activity'],
      dtype=object)

In [ ]:
#Para poder ver mejor los datos vamos a cambiar las preguntas:
categories_to_replace = {
'Percent of adults aged 18 years and older who have obesity': 'Obesity',
'Percent of adults aged 18 years and older who have an overweight classification': 'Overweight',
'Percent of adults who report consuming fruit less than one time daily': 'Low Fruit',
'Percent of adults who report consuming vegetables less than one time daily': 'Low Vegetable',
'Percent of adults who engage in muscle-strengthening activities on 2 or more days a week': 'Muscle Strengthening',
'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)': '150 Minutes Activity',
'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week': '150 Minutes + Muscle Strengthening',
'Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)': '300 Minutes Activity',
'Percent of adults who engage in no leisure-time physical activity': 'NoExercise'
}


obesidad_recortado['Question'] = obesidad_recortado['Question'].replace(categories_to_replace)

C:\Users\Equipo\AppData\Local\Temp\ipykernel_10344\2016283547.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  obesidad_recortado['Question'] = obesidad_recortado['Question'].replace(categories_to_replace)

Ahora la tabla tiene otra pinta. Lo vemos todo mucho más claro. Incluso podemos juntar las columnas YearStart, YearEnd y LocationAbbr en una sola. Para tener menos columnas.

In [ ]:
obesidad_recortado.head()

   YearStart  YearEnd LocationAbbr Question  Data_Value        Stratification1
0       2011     2011           AL  Obesity        32.0                  Total
1       2011     2011           AL  Obesity        32.3                   Male
2       2011     2011           AL  Obesity        31.8                 Female
3       2011     2011           AL  Obesity        33.6  Less than high school
4       2011     2011           AL  Obesity        32.8   High school graduate

In [ ]:
obesidad_recortado['YearLoc'] = obesidad_recortado['YearStart'].astype(str)+obesidad_recortado['YearEnd'].astype(str)+obesidad_recortado['LocationAbbr']
obesidad_recortado.drop(columns=['YearStart','YearEnd','LocationAbbr'],inplace=True)

C:\Users\Equipo\AppData\Local\Temp\ipykernel_10344\1799415316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  obesidad_recortado['YearLoc'] = obesidad_recortado['YearStart'].astype(str)+obesidad_recortado['YearEnd'].astype(str)+obesidad_recortado['LocationAbbr']
C:\Users\Equipo\AppData\Local\Temp\ipykernel_10344\1799415316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  obesidad_recortado.drop(columns=['YearStart','YearEnd','LocationAbbr'],inplace=True)

In [ ]:
obesidad_recortado.head()

  Question  Data_Value        Stratification1     YearLoc
0  Obesity        32.0                  Total  20112011AL
1  Obesity        32.3                   Male  20112011AL
2  Obesity        31.8                 Female  20112011AL
3  Obesity        33.6  Less than high school  20112011AL
4  Obesity        32.8   High school graduate  20112011AL

Ahora que hemos hecho esto, vamos a usar pivot_table para pivotar la tabla. Pivotar una matriz o una tabla es cambiar lo que está en filas a las columnas. Es decir, los datos que tenemos uno en cada fila pasaremos a tenerlos uno en cada columna. Para ello, tenemos que especificar el dataframe que queremos usar, values es de que columna se van a sacar los valores para rellenar la tabla. index es el índice, es decir, lo que va a tener en común cada fila (en este caso, tendremos, por ejemplo todos los datos de Arkansas, 2012 para hombres, o Missouri, 2013 para personas sin el graudado escolar). columns será la columna de donde se van a sacar los nombres de las columnas. En este caso ponemos Question, para que, por cada valor único de la columna Question, tengamos un nombre de columna nuevo.

In [ ]:
obesidad = pd.pivot_table(obesidad_recortado, values="Data_Value", index=["YearLoc",'Stratification1'], columns=["Question"])

Como podemos ver al hacer head, ahora si que nos ha quedado bien. Solo nos queda un cosa, eliminar YearLoc, que no lo queremos para nada y pasar Stratification1 a una columna normal (ahora están las dos como índices)

In [ ]:
obesidad.head()

Question                       150 Minutes + Muscle Strengthening  \
YearLoc    Stratification1
20112011AK $15,000 - $24,999                                 17.3
           $25,000 - $34,999                                 20.2
           $35,000 - $49,999                                 21.6
           $50,000 - $74,999                                 26.1
           $75,000 or greater                                30.8

Question                       150 Minutes Activity  300 Minutes Activity  \
YearLoc    Stratification1
20112011AK $15,000 - $24,999                   51.8                  32.7
           $25,000 - $34,999                   57.9                  38.2
           $35,000 - $49,999                   55.1                  34.1
           $50,000 - $74,999                   59.3                  32.6
           $75,000 or greater                  63.2                  44.8

Question                       Low Fruit  Low Vegetable  Muscle Strengthening  \
YearLoc    Stratification1
20112011AK $15,000 - $24,999        44.6           26.1                  28.1
           $25,000 - $34,999        45.6           24.4                  24.5
           $35,000 - $49,999        37.2           19.4                  31.4
           $50,000 - $74,999        39.1           16.5                  37.7
           $75,000 or greater       31.9           11.8                  38.0

Question                       NoExercise  Obesity  Overweight
YearLoc    Stratification1
20112011AK $15,000 - $24,999         24.6     30.2        33.5
           $25,000 - $34,999         25.8     32.2        38.1
           $35,000 - $49,999         25.7     24.5        42.3
           $50,000 - $74,999         19.2     27.8        41.6
           $75,000 or greater        17.1     26.9        39.9

Al hacer reset_index(), las dos columnas que están como índice pasan a ser columnas normales. Después solo queda borrar la que no necesitamos.

In [ ]:
obesidad = obesidad.reset_index()

In [ ]:
obesidad.drop(['YearLoc'],axis=1,inplace=True)

In [ ]:
obesidad.head()

Question,Stratification1,150 Minutes + Muscle Strengthening,150 Minutes Activity,300 Minutes Activity,Low Fruit,Low Vegetable,Muscle Strengthening,NoExercise,Obesity,Overweight
0,"$15,000 - $24,999",17.3,51.8,32.7,44.6,26.1,28.1,24.6,30.2,33.5
1,"$25,000 - $34,999",20.2,57.9,38.2,45.6,24.4,24.5,25.8,32.2,38.1
2,"$35,000 - $49,999",21.6,55.1,34.1,37.2,19.4,31.4,25.7,24.5,42.3
3,"$50,000 - $74,999",26.1,59.3,32.6,39.1,16.5,37.7,19.2,27.8,41.6
4,"$75,000 or greater",30.8,63.2,44.8,31.9,11.8,38.0,17.1,26.9,39.9

Como Stratification1 es una columna categórica vamos a hacer get_dummies para transformarla en numérica.

In [ ]:
obesidad = pd.get_dummies(obesidad,dtype=int)

In [ ]:
obesidad.head()

,150 Minutes + Muscle Strengthening,150 Minutes Activity,300 Minutes Activity,Low Fruit,Low Vegetable,Muscle Strengthening,NoExercise,Obesity,Overweight,"Stratification1_$15,000 - $24,999",...,Stratification1_High school graduate,Stratification1_Hispanic,"Stratification1_Less than $15,000",Stratification1_Less than high school,Stratification1_Male,Stratification1_Non-Hispanic Black,Stratification1_Non-Hispanic White,Stratification1_Other,Stratification1_Some college or technical school,Stratification1_Total
0,17.3,51.8,32.7,44.6,26.1,28.1,24.6,30.2,33.5,1,...,0,0,0,0,0,0,0,0,0,0
1,20.2,57.9,38.2,45.6,24.4,24.5,25.8,32.2,38.1,0,...,0,0,0,0,0,0,0,0,0,0
2,21.6,55.1,34.1,37.2,19.4,31.4,25.7,24.5,42.3,0,...,0,0,0,0,0,0,0,0,0,0
3,26.1,59.3,32.6,39.1,16.5,37.7,19.2,27.8,41.6,0,...,0,0,0,0,0,0,0,0,0,0
4,30.8,63.2,44.8,31.9,11.8,38.0,17.1,26.9,39.9,0,...,0,0,0,0,0,0,0,0,0,0

Ahora tenemos un problema. La mitad de las filas tienen muy pocas columnas rellenas, el resto son nulos. Eso es un problema porque si rellenamos, nos estamos inventando la mitad de los datos. Si borramos columnas nos estamos cargando columnas que, aunque tengan la mitad de los datos nulos, tienen bastante correlación con el objetivo (obesidad) y si borramos las filas nos cargamos la mitad del dataset. Vamos a optar por borrar las filas como un mal menor.

In [ ]:
obesidad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8153 entries, 0 to 8152
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   150 Minutes + Muscle Strengthening                3991 non-null   float64
 1   150 Minutes Activity                              3994 non-null   float64
 2   300 Minutes Activity                              3991 non-null   float64
 3   Low Fruit                                         3998 non-null   float64
 4   Low Vegetable                                     3996 non-null   float64
 5   Muscle Strengthening                              4003 non-null   float64
 6   NoExercise                                        8119 non-null   float64
 7   Obesity                                           8127 non-null   float64
 8   Overweight                                        8127 non-null   float64
 9   Stratification1_$15,000 - $24,999                 8153 non-null   int64
 10  Stratification1_$25,000 - $34,999                 8153 non-null   int64
 11  Stratification1_$35,000 - $49,999                 8153 non-null   int64
 12  Stratification1_$50,000 - $74,999                 8153 non-null   int64
 13  Stratification1_$75,000 or greater                8153 non-null   int64
 14  Stratification1_18 - 24                           8153 non-null   int64
 15  Stratification1_2 or more races                   8153 non-null   int64
 16  Stratification1_25 - 34                           8153 non-null   int64
 17  Stratification1_35 - 44                           8153 non-null   int64
 18  Stratification1_45 - 54                           8153 non-null   int64
 19  Stratification1_55 - 64                           8153 non-null   int64
 20  Stratification1_65 or older                       8153 non-null   int64
 21  Stratification1_American Indian/Alaska Native     8153 non-null   int64
 22  Stratification1_Asian                             8153 non-null   int64
 23  Stratification1_College graduate                  8153 non-null   int64
 24  Stratification1_Data not reported                 8153 non-null   int64
 25  Stratification1_Female                            8153 non-null   int64
 26  Stratification1_Hawaiian/Pacific Islander         8153 non-null   int64
 27  Stratification1_High school graduate              8153 non-null   int64
 28  Stratification1_Hispanic                          8153 non-null   int64
 29  Stratification1_Less than $15,000                 8153 non-null   int64
 30  Stratification1_Less than high school             8153 non-null   int64
 31  Stratification1_Male                              8153 non-null   int64
 32  Stratification1_Non-Hispanic Black                8153 non-null   int64
 33  Stratification1_Non-Hispanic White                8153 non-null   int64
 34  Stratification1_Other                             8153 non-null   int64
 35  Stratification1_Some college or technical school  8153 non-null   int64
 36  Stratification1_Total                             8153 non-null   int64
dtypes: float64(9), int64(28)
memory usage: 2.3 MB

In [ ]:
obesidad.dropna(inplace=True)

In [ ]:
obesidad.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3980 entries, 0 to 6753
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   150 Minutes + Muscle Strengthening                3980 non-null   float64
 1   150 Minutes Activity                              3980 non-null   float64
 2   300 Minutes Activity                              3980 non-null   float64
 3   Low Fruit                                         3980 non-null   float64
 4   Low Vegetable                                     3980 non-null   float64
 5   Muscle Strengthening                              3980 non-null   float64
 6   NoExercise                                        3980 non-null   float64
 7   Obesity                                           3980 non-null   float64
 8   Overweight                                        3980 non-null   float64
 9   Stratification1_$15,000 - $24,999                 3980 non-null   int64
 10  Stratification1_$25,000 - $34,999                 3980 non-null   int64
 11  Stratification1_$35,000 - $49,999                 3980 non-null   int64
 12  Stratification1_$50,000 - $74,999                 3980 non-null   int64
 13  Stratification1_$75,000 or greater                3980 non-null   int64
 14  Stratification1_18 - 24                           3980 non-null   int64
 15  Stratification1_2 or more races                   3980 non-null   int64
 16  Stratification1_25 - 34                           3980 non-null   int64
 17  Stratification1_35 - 44                           3980 non-null   int64
 18  Stratification1_45 - 54                           3980 non-null   int64
 19  Stratification1_55 - 64                           3980 non-null   int64
 20  Stratification1_65 or older                       3980 non-null   int64
 21  Stratification1_American Indian/Alaska Native     3980 non-null   int64
 22  Stratification1_Asian                             3980 non-null   int64
 23  Stratification1_College graduate                  3980 non-null   int64
 24  Stratification1_Data not reported                 3980 non-null   int64
 25  Stratification1_Female                            3980 non-null   int64
 26  Stratification1_Hawaiian/Pacific Islander         3980 non-null   int64
 27  Stratification1_High school graduate              3980 non-null   int64
 28  Stratification1_Hispanic                          3980 non-null   int64
 29  Stratification1_Less than $15,000                 3980 non-null   int64
 30  Stratification1_Less than high school             3980 non-null   int64
 31  Stratification1_Male                              3980 non-null   int64
 32  Stratification1_Non-Hispanic Black                3980 non-null   int64
 33  Stratification1_Non-Hispanic White                3980 non-null   int64
 34  Stratification1_Other                             3980 non-null   int64
 35  Stratification1_Some college or technical school  3980 non-null   int64
 36  Stratification1_Total                             3980 non-null   int64
dtypes: float64(9), int64(28)
memory usage: 1.2 MB

Ahora tenemos que generar los conjuntos X e y, escalar X, separar tran y test y empezar a entrenar nuestros 3 modelos de regresión, SVR, DecisionTreeRegressor y RandomForestRegressor.

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

y = obesidad['Obesity'].to_frame()
X = obesidad.drop(['Obesity'],axis=1)
X = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.svm import SVR
svr_reg = SVR(C=100,gamma=0.01, epsilon=0.8,kernel='rbf')
svr_reg.fit(X_train,y_train)

y_pred = svr_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

c:\Users\Equipo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.757455541968691

In [ ]:
from sklearn.tree import DecisionTreeRegressor
#tree_reg = DecisionTreeRegressor(max_depth=15, min_samples_split=20, min_samples_leaf=2,random_state=42)
tree_reg = DecisionTreeRegressor(min_samples_split=400,random_state=42)
tree_reg.fit(X_train, y_train)
y_pred = tree_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6493410136802531

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rnd_reg = RandomForestRegressor(n_estimators=1000, n_jobs=-1,random_state=42)
rnd_reg.fit(X_train,y_train)
y_pred = rnd_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

c:\Users\Equipo\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.7433827969974325