# Actividad 2_10: Repaso

En esta Actividad vamos a repasar los conceptos que hemos visto hasta ahora en clase.

Descarga el archivo "Top 100 Cryptocurrency 2022.csv" que se adjunta con la tarea y realiza los siguientes apartados:

Debes escribir una programa que realice las siguientes tareas:

1. Importar los datos del dataset adjunto con la tarea y guardarlos en un DataFrame.
2. Crea una función que reciba un número (debes tratar la excepción en caso de que no sea un entero) y el dataframe y devuelva un DataFrame en el que haya eliminado todas las criptomonedas que no superen el número pasado como parámetro. Prueba la función.
3. Normaliza la columna del precio actual de las criptomonedas ("Price") y muestre una gráfica con los valores de las 10 que tienen mayor valor.
4. Predice el próximo valor de las criptomonedas suponiendo que la variación de las próximas 24h  va a ser la misma que en las anteriores ('Changes 24H') y mételo en una columna nueva.

In [1]:
import pandas as pd

df = pd.read_csv("Top 100 Cryptocurrency 2022.csv")
df.head(100)

,Ranking,Crypto Name,Price,Changes 24H,Changes 7D,Changes 30D,Changes 1Y,Market Cap,Volume 24H,Available Supply
0,1,BITCOIN,"$36,983",-2.97%,1.96%,-20.08%,8.25%,$701.49 B,$13.01 B,18.94 M BTC
1,2,WRAPPED BITCOIN,"$37,019",-2.84%,1.84%,-20.13%,8.26%,$10.04 B,$253.14 M,271.16 K WBTC
2,3,HUOBI BTC,"$36,942",-4.24%,1.37%,-20.39%,7.82%,$1.47 B,$29.51 M,39.88 K HBTC
3,4,ETHEREUM,"$2,510",-3.64%,-1.28%,-32.04%,82.54%,$298.87 B,$10.00 B,119.38 M ETH
4,5,LIDO STAKED ETHER,"$2,494",-3.23%,-1.84%,-31.98%,95.88%,$4.48 B,$2.07 M,1.79 M STETH
...,...,...,...,...,...,...,...,...,...,...
95,96,ECOMI,$0.01,-6.53%,4.42%,9.77%,9999.99%,$3.99 B,$4.01 M,581.91 B OMI
96,97,BITTORRENT,$0.00,$0.00,-1.10%,-19.83%,481.49%,$2.04 B,$283.87 K,932.50 B BTTOLD
97,98,SAFEMOON,$0.00,-3.19%,-3.72%,-34.03%,0.00%,$933.63 M,$410.28 K,566.50 B SFM
98,99,ECASH,$0.00,-3.71%,-1.41%,-32.83%,0.00%,$1.40 B,$19.78 M,18.97 T XEC
99,100,SHIBA INU,$0.00,-6.68%,-8.16%,-38.56%,9999.99%,$11.27 B,$443.94 M,549.15 T SHIB

In [ ]:

df.head(1000)

,Ranking,Crypto Name,Price,Changes 24H,Changes 7D,Changes 30D,Changes 1Y,Market Cap,Volume 24H,Available Supply
0,1,BITCOIN,36983.00,-2.97%,1.96%,-20.08%,8.25%,$701.49 B,$13.01 B,18.94 M BTC
1,2,WRAPPED BITCOIN,37019.00,-2.84%,1.84%,-20.13%,8.26%,$10.04 B,$253.14 M,271.16 K WBTC
2,3,HUOBI BTC,36942.00,-4.24%,1.37%,-20.39%,7.82%,$1.47 B,$29.51 M,39.88 K HBTC
3,4,ETHEREUM,2510.00,-3.64%,-1.28%,-32.04%,82.54%,$298.87 B,$10.00 B,119.38 M ETH
4,5,LIDO STAKED ETHER,2494.00,-3.23%,-1.84%,-31.98%,95.88%,$4.48 B,$2.07 M,1.79 M STETH
...,...,...,...,...,...,...,...,...,...,...
95,96,ECOMI,0.01,-6.53%,4.42%,9.77%,9999.99%,$3.99 B,$4.01 M,581.91 B OMI
96,97,BITTORRENT,0.00,$0.00,-1.10%,-19.83%,481.49%,$2.04 B,$283.87 K,932.50 B BTTOLD
97,98,SAFEMOON,0.00,-3.19%,-3.72%,-34.03%,0.00%,$933.63 M,$410.28 K,566.50 B SFM
98,99,ECASH,0.00,-3.71%,-1.41%,-32.83%,0.00%,$1.40 B,$19.78 M,18.97 T XEC
99,100,SHIBA INU,0.00,-6.68%,-8.16%,-38.56%,9999.99%,$11.27 B,$443.94 M,549.15 T SHIB

In [20]:


def recibir_num(num):
    df["Price"] = pd.to_numeric(df["Price"].replace(r"[$,""]", "", regex=True))
    for i, row in df.iterrows():
        if row["Price"] < num:
            df.drop(i, inplace=True)

    return df.head()

recibir_num(36982.00)

,Ranking,Crypto Name,Price,Changes 24H,Changes 7D,Changes 30D,Changes 1Y,Market Cap,Volume 24H,Available Supply
0,1,BITCOIN,36983.0,-2.97%,1.96%,-20.08%,8.25%,$701.49 B,$13.01 B,18.94 M BTC
1,2,WRAPPED BITCOIN,37019.0,-2.84%,1.84%,-20.13%,8.26%,$10.04 B,$253.14 M,271.16 K WBTC