## Actividad 3_11

<div style="border-style:groove;border-width:thin;padding:10px">

Trabajamos en una empresa de alquiler de bicicletas en Seul. El departamento de mantenimiento de bicicletas ha pedido a nuestro departamento de DataScience si es posible poder saber, a priori, cuantas bicicletas tiene que haber disponibles porque ellos tienen que ir retirando bicicletas para repararlas. Tenemos los datos que se muestran a continuación. ¿Será posible saber cuantas tienen que tener en circulación?

</div>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.datasets import make_moons, make_circles
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_graphviz, DecisionTreeRegressor

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_absolute_error, r2_score, mean_squared_error

In [3]:
import pandas as pd
bicicletas = pd.read_csv("SeoulBikeData.csv", sep=',',encoding='latin-1')
bicicletas.head()

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [4]:
bicicletas.drop(columns=["Date"], inplace=True)

In [5]:
bicicletas.info()
bicicletas.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Rented Bike Count          8760 non-null   int64
 1   Hour                       8760 non-null   int64
 2   Temperature(°C)            8760 non-null   float64
 3   Humidity(%)                8760 non-null   int64
 4   Wind speed (m/s)           8760 non-null   float64
 5   Visibility (10m)           8760 non-null   int64
 6   Dew point temperature(°C)  8760 non-null   float64
 7   Solar Radiation (MJ/m2)    8760 non-null   float64
 8   Rainfall(mm)               8760 non-null   float64
 9   Snowfall (cm)              8760 non-null   float64
 10  Seasons                    8760 non-null   object
 11  Holiday                    8760 non-null   object
 12  Functioning Day            8760 non-null   object
dtypes: float64(6), int64(4), object(3)
memory usage: 889.8+ KB

(8760, 13)

In [6]:
bicicletas.head()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [7]:
bicicletas = pd.get_dummies(bicicletas, columns=["Seasons", "Holiday"], dtype=int)

In [8]:
bicicletas['Functioning Day'] = bicicletas['Functioning Day'].replace({'Yes': 1, 'No': 0})

/tmp/ipykernel_16738/1704255731.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bicicletas['Functioning Day'] = bicicletas['Functioning Day'].replace({'Yes': 1, 'No': 0})

In [9]:
bicicletas.corr(numeric_only=True)['Rented Bike Count'].abs().sort_values(ascending=False)[1:]

Temperature(°C)              0.538558
Seasons_Winter               0.424925
Hour                         0.410257
Dew point temperature(°C)    0.379788
Seasons_Summer               0.296549
Solar Radiation (MJ/m2)      0.261837
Functioning Day              0.203943
Humidity(%)                  0.199780
Visibility (10m)             0.199280
Snowfall (cm)                0.141804
Rainfall(mm)                 0.123074
Wind speed (m/s)             0.121108
Seasons_Autumn               0.102753
Holiday_Holiday              0.072338
Holiday_No Holiday           0.072338
Seasons_Spring               0.022888
Name: Rented Bike Count, dtype: float64

In [10]:
X = bicicletas.drop(['Rented Bike Count'],axis=1)
y = bicicletas['Rented Bike Count'].to_frame()

In [11]:
escalador = StandardScaler()
X = escalador.fit_transform(X)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42)

In [ ]:
tree_clf = DecisionTreeRegressor(criterion='squared_error', max_depth=15, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=50, random_state=42)
tree_clf.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=15, min_samples_leaf=5, min_samples_split=50)

In [14]:
y_pred = tree_clf.predict(X_test)

In [15]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"R2: {r2:.4f}")

MSE: 82776.6619
RMSE: 287.7093
MAE: 174.0223
R2: 0.8013

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

def mejor_combinacion_grid_search(tipo='regressor'):
    """
    Encuentra la mejor combinación usando GridSearchCV (prueba TODAS las combinaciones).
    """
    # Definir el espacio de búsqueda
    param_grid = {
        'max_depth': [3, 5, 10, 15, 20, None],
        'min_samples_split': [2, 10, 50, 100],
        'min_samples_leaf': [1, 5, 20, 50],
        'max_leaf_nodes': [None, 8, 16, 32, 64]
    }
    
    if tipo == 'regressor':
        param_grid['criterion'] = ['squared_error', 'friedman_mse', 'absolute_error']
        model = DecisionTreeRegressor(random_state=42)
        scoring = 'r2'
    else:
        param_grid['criterion'] = ['gini', 'entropy']
        model = DecisionTreeClassifier(random_state=42)
        scoring = 'accuracy'
    
    print(f"\n{'='*80}")
    print(f"GRID SEARCH - {tipo.upper()}")
    print(f"Total de combinaciones a probar: {6 * 3 * 4 * 4 * 5}")
    print(f"{'='*80}\n")
    
    # Realizar Grid Search
    grid_search = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring=scoring,
        cv=5,  # Validación cruzada con 5 folds
        n_jobs=-1,  # Usar todos los procesadores
        verbose=2
    )
    
    grid_search.fit(X_train, y_train)
    
    # Resultados
    print(f"\n{'='*80}")
    print(f"MEJOR COMBINACIÓN ENCONTRADA (Grid Search)")
    print(f"{'='*80}")
    print(f"Mejor score (CV): {grid_search.best_score_:.4f}")
    print(f"\nHiperparámetros:")
    for param, valor in grid_search.best_params_.items():
        print(f"  - {param:20}: {valor}")
    
    # Evaluar en test
    y_pred = grid_search.best_estimator_.predict(X_test)
    if tipo == 'regressor':
        test_score = r2_score(y_test, y_pred)
        print(f"\nR² en test: {test_score:.4f}")
    else:
        test_score = accuracy_score(y_test, y_pred)
        print(f"\nAccuracy en test: {test_score:.4f}")
    
    print(f"{'='*80}\n")
    
    return grid_search.best_params_, grid_search.best_estimator_


# ========== USO ==========

# Para REGRESIÓN:
mejores_params, mejor_modelo = mejor_combinacion_grid_search(tipo='regressor')

# Para CLASIFICACIÓN:
# mejores_params, mejor_modelo = mejor_combinacion_grid_search(tipo='classifier')

================================================================================
GRID SEARCH - REGRESSOR
Total de combinaciones a probar: 1440
================================================================================

Fitting 5 folds for each of 1440 candidates, totalling 7200 fits
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=50; total time=   0.0s[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=50; total time=   0.0s

[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=50, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=5, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=20, min_samples_split=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=2; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=50; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=10; total time=   0.0s
[CV] END criterion=squared_error, max_depth=3, max_leaf_nodes=8, min_samples_leaf=50, min_samples_split=50; total time=   0.0s