# Actividad 2_8: 

Descarga los dos ficheros adjuntos que encontrarás con la tarea. Uno de ellos contiene un dataset con el precio mensual de la cuenta de Netflix por países. El otro contiene datos sobre los salarios por países. El objetivo de esta actividad es contestar a la siguiente pregunta. ¿Existe relación entre la media o la mediana de los salarios de los países y la cuota mensual que se paga por Netflix?

Debes escribir un programa que realice las siguientes tareas:

1. Importar los dos datasets adjuntos con la tarea y guardarlos en dos Dataframes. Analiza los datos.
2. Crea un DataFrame que incluya una columna con el coste mensual standars de Netflix, otra con el salario medio y otra con la mediana.
3. Normaliza los datos del DataFrame creado en el punto 3. Normalizar los datos consiste en escalar los valores para que tengan un rango similar. En este caso nos sirve para poder comparar el coste mensual de Netflix con el salario de una persona (que tendrán inicialmente un rango muy distinto). Hay muchos métodos para normalizar. En pandas tenemos algunos métodos que puedes encontrar en el enlace a continuación. Puedes usar uno o probar varios. Si haces esto último debes hacer varios métodos.

https://www.geeksforgeeks.org/normalize-a-column-in-pandas/

4. Finalmente debes pintar una gráfica con los datos por países ya normalizados y contestar a la pregunta. ¿Existe relación entre lo que gana una persona en cada país y lo que debe pagar por Netflix?

In [ ]:
import pandas as pd

df_netflix = pd.read_csv("Netflix subscription fee Dec-2021.csv")
df_salarios = pd.read_csv("salaries_by_country_2021.csv")

df_netflix.head()
#print(df_salarios.head())

,Country_code,Country,Total Library Size,No. of TV Shows,No. of Movies,Cost Per Month - Basic ($),Cost Per Month - Standard ($),Cost Per Month - Premium ($)
0,ar,Argentina,4760,3154,1606,3.74,6.30,9.26
1,au,Australia,6114,4050,2064,7.84,12.12,16.39
2,at,Austria,5640,3779,1861,9.03,14.67,20.32
3,be,Belgium,4990,3374,1616,10.16,15.24,20.32
4,bo,Bolivia,4991,3155,1836,7.99,10.99,13.99

In [9]:
for pais in df_netflix["Country"].to_list():
    if pais in df_salarios["country"].to_list():
        print(pais)

df_completo = df_netflix.merge(df_salarios, how="inner",left_on="Country", right_on="country")
df_completo.head()

Argentina
Australia
Austria
Belgium
Bolivia
Brazil
Bulgaria
Canada
Chile
Colombia
Costa Rica
Croatia
Denmark
Ecuador
Estonia
Finland
France
Germany
Greece
Guatemala
Honduras
Hungary
Iceland
India
Ireland
Israel
Italy
Japan
Latvia
Lithuania
Malaysia
Mexico
Moldova
Netherlands
Norway
Paraguay
Peru
Philippines
Poland
Portugal
Romania
Russia
Slovakia
South Africa
South Korea
Spain
Sweden
Switzerland
Taiwan
Thailand
Turkey
Ukraine
United Kingdom
United States
Uruguay
Venezuela

,Country_code,Country,Total Library Size,No. of TV Shows,No. of Movies,Cost Per Month - Basic ($),Cost Per Month - Standard ($),Cost Per Month - Premium ($),country,medianIncome,meanIncome,gdpPerCapitaPPP,pop2021
0,ar,Argentina,4760,3154,1606,3.74,6.30,9.26,Argentina,5319,6935,0,45605.826
1,au,Australia,6114,4050,2064,7.84,12.12,16.39,Australia,17076,21329,53381,25788.215
2,at,Austria,5640,3779,1861,9.03,14.67,20.32,Austria,18405,20718,60418,9043.070
3,be,Belgium,4990,3374,1616,10.16,15.24,20.32,Belgium,16157,17917,56348,11632.326
4,bo,Bolivia,4991,3155,1836,7.99,10.99,13.99,Bolivia,3631,4787,9110,11832.940